In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import train_test_split

In [3]:
df= pd.read_csv("C:\\Users\\ONEEKA\\Downloads\\penguins_manipulated_1241_rows.csv")
#bankdata = pd.read_csv("C:\\Users\\ONEEKA\\Downloads\\penguins.csv")

In [4]:
df.shape

(1241, 7)

In [5]:
df.head(10)

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Gentoo     Biscoe          40.175         18.135                208   
1  Adelie     Biscoe          41.852         17.043                189   
2  Gentoo     Biscoe          55.965         19.059                217   
3  Gentoo      Dream          49.238         12.544                219   
4  Adelie     Biscoe          49.644         17.566                216   
5  Gentoo  Torgersen          36.128         21.729                211   
6  Adelie     Biscoe          44.257         21.103                186   
7  Adelie      Dream          51.109         17.276                217   
8  Adelie      Dream          43.060         20.012                187   
9  Gentoo      Dream          47.764         15.143                227   

   body_mass_g     sex  
0         3527    male  
1         3899  female  
2         5612    male  
3         6239    male  
4         5380    male  
5         5390  female  
6         3746  female  
7         5668    male  
8         2763  female  
9         5577    male

In [6]:
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()

# Create new columns for encoded values
df['Species_n'] = LE.fit_transform(df['species'])
df['Island_n']  = LE.fit_transform(df['island'])

In [7]:
df['Sex_n'] = LE.fit_transform(df['sex'])

In [8]:
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        Gentoo     Biscoe          40.175         18.135                208   
1        Adelie     Biscoe          41.852         17.043                189   
2        Gentoo     Biscoe          55.965         19.059                217   
3        Gentoo      Dream          49.238         12.544                219   
4        Adelie     Biscoe          49.644         17.566                216   
...         ...        ...             ...            ...                ...   
1236     Gentoo      Dream          43.350         17.662                182   
1237  Chinstrap     Biscoe          52.041         16.966                222   
1238     Adelie     Biscoe          44.232         12.014                203   
1239  Chinstrap     Biscoe          34.942         16.963                182   
1240     Gentoo  Torgersen          38.434         19.394                182   

      body_mass_g     sex  Species_n  Island_n  Sex_n  
0            3527    male          2         0      1  
1            3899  female          0         0      0  
2            5612    male          2         0      1  
3            6239    male          2         1      1  
4            5380    male          0         0      1  
...           ...     ...        ...       ...    ...  
1236         4584    male          2         1      1  
1237         5189    male          1         0      1  
1238         4852  female          0         0      0  
1239         3115  female          1         0      0  
1240         3262  female          2         2      0  

[1241 rows x 10 columns]

In [9]:
df.drop(axis=1,columns='sex',inplace=True)
df.drop(axis=1,columns='species',inplace=True)
df.drop(axis=1,columns='island',inplace=True)

In [10]:
df

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0             40.175         18.135                208         3527   
1             41.852         17.043                189         3899   
2             55.965         19.059                217         5612   
3             49.238         12.544                219         6239   
4             49.644         17.566                216         5380   
...              ...            ...                ...          ...   
1236          43.350         17.662                182         4584   
1237          52.041         16.966                222         5189   
1238          44.232         12.014                203         4852   
1239          34.942         16.963                182         3115   
1240          38.434         19.394                182         3262   

      Species_n  Island_n  Sex_n  
0             2         0      1  
1             0         0      0  
2             2         0      1  
3             2         1      1  
4             0         0      1  
...         ...       ...    ...  
1236          2         1      1  
1237          1         0      1  
1238          0         0      0  
1239          1         0      0  
1240          2         2      0  

[1241 rows x 7 columns]

In [11]:
X = df.drop('Species_n', axis=1)
y = df['Species_n']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20,random_state=5)

In [12]:
# PROCESS 1
model = BaggingClassifier(SVC())

In [13]:
kfold=model_selection.KFold(n_splits=10)
results = model_selection.cross_val_score(model,X_train, y_train, cv=kfold)

In [14]:
print("Results:", results)
print("Mean Results:", results.mean())

Results: [0.47       0.48       0.41414141 0.52525253 0.38383838 0.57575758
 0.43434343 0.42424242 0.46464646 0.51515152]
Mean Results: 0.4687373737373738


In [15]:
#PROCESS 2
model = BaggingClassifier(SVC())
model.fit(X_train, y_train)

BaggingClassifier(estimator=SVC())

In [16]:
y_pred = model.predict(X_test)

In [17]:
model.score(X_test, y_test)

0.42971887550200805

In [18]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[107   0   0]
 [ 22   0   0]
 [120   0   0]]
              precision    recall  f1-score   support

           0       0.43      1.00      0.60       107
           1       0.00      0.00      0.00        22
           2       0.00      0.00      0.00       120

    accuracy                           0.43       249
   macro avg       0.14      0.33      0.20       249
weighted avg       0.18      0.43      0.26       249



D:\Anaconda_Navigator\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\Anaconda_Navigator\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\Anaconda_Navigator\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
