In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split

In [17]:
df= pd.read_csv("C:\\Users\\ONEEKA\\Downloads\\penguins.csv")

In [18]:
df.shape

(344, 7)

In [19]:
df.head(10)

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7                181   
1  Adelie  Torgersen            39.5           17.4                186   
2  Adelie  Torgersen            40.3           18.0                195   
3  Adelie  Torgersen            41.5           20.0                186   
4  Adelie  Torgersen            36.7           19.3                193   
5  Adelie  Torgersen            39.3           20.6                190   
6  Adelie  Torgersen            38.9           17.8                181   
7  Adelie  Torgersen            39.2           19.6                195   
8  Adelie  Torgersen            34.1           18.1                193   
9  Adelie  Torgersen            42.0           20.2                190   

   body_mass_g  Gender  
0         3750    male  
1         3800  female  
2         3250  female  
3         3450     NaN  
4         3450  female  
5         3650    male  
6         3625  female  
7         4675    male  
8         3475     NaN  
9         4250     NaN

In [20]:
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()

# Create new columns for encoded values
df['Species_n'] = LE.fit_transform(df['species'])
df['Island_n']  = LE.fit_transform(df['island'])
df['Gender_n'] = LE.fit_transform(df['Gender'])

In [21]:
df.drop(axis=1,columns='Gender',inplace=True)
df.drop(axis=1,columns='species',inplace=True)
df.drop(axis=1,columns='island',inplace=True)

In [22]:
df

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Species_n  \
0              39.1           18.7                181         3750          0   
1              39.5           17.4                186         3800          0   
2              40.3           18.0                195         3250          0   
3              41.5           20.0                186         3450          0   
4              36.7           19.3                193         3450          0   
..              ...            ...                ...          ...        ...   
339            55.8           19.8                207         4000          1   
340            43.5           18.1                202         3400          1   
341            49.6           18.2                193         3775          1   
342            50.8           19.0                210         4100          1   
343            50.2           18.7                198         3775          1   

     Island_n  Gender_n  
0           2         1  
1           2         0  
2           2         0  
3           2         2  
4           2         0  
..        ...       ...  
339         1         1  
340         1         0  
341         1         1  
342         1         1  
343         1         0  

[344 rows x 7 columns]

In [57]:
X = df.drop('Species_n', axis=1)
y = df['Species_n']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20,random_state=5)

In [58]:
# PROCESS 1
#seed=7
num_trees=10
model = AdaBoostClassifier(n_estimators=num_trees)

In [59]:
input = df.fillna(df.mean())

In [60]:
kfold=model_selection.KFold(n_splits=5)
results = model_selection.cross_val_score(model,X_train, y_train, cv=kfold)

D:\Anaconda_Navigator\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
D:\Anaconda_Navigator\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
D:\Anaconda_Navigator\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
D:\Anaconda_Navigator\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
D:\Anaconda_Navigator\Li

In [61]:
print("Results:", results)
print("Mean Results:", results.mean())

Results: [0.92727273 0.74545455 0.72727273 0.81818182 0.90909091]
Mean Results: 0.8254545454545456


In [62]:
#PROCESS 2
model = AdaBoostClassifier(n_estimators=num_trees)
model.fit(X_train, y_train)

D:\Anaconda_Navigator\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier(n_estimators=10)

In [63]:
y_pred = model.predict(X_test)

In [64]:
model.score(X_test, y_test)

0.7681159420289855

In [65]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[32  0  0]
 [15  0  0]
 [ 1  0 21]]
              precision    recall  f1-score   support

           0       0.67      1.00      0.80        32
           1       0.00      0.00      0.00        15
           2       1.00      0.95      0.98        22

    accuracy                           0.77        69
   macro avg       0.56      0.65      0.59        69
weighted avg       0.63      0.77      0.68        69



D:\Anaconda_Navigator\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\Anaconda_Navigator\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\Anaconda_Navigator\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
